ProjectEvergreen/wcc

docs/components/header.js

N / A
Noticed the header was flashing on reload and that the GitHub badge was looking a little stretched out now that the repo is public.
1. Gave header a min height (maybe we should move all styles globally in a <style> tag?)
1. Adjust badge styles and kept within aspect ratio

minor header enhancements

---

docs/components/footer.js
docs/components/header.js
docs/components/navigation.js
docs/layout.js
src/dom-shim.js
test/cases/attributes/attributes.spec.js
test/cases/attributes/src/components/counter.js
test/cases/attributes/src/index.js
test/cases/children-and-slots/children-and-slots.spec.js
test/cases/children-and-slots/src/pages/index.js
test/cases/get-data/get-data.spec.js
test/cases/get-data/src/components/counter.js
test/cases/get-data/src/index.js
test/cases/light-dom/light-dom.spec.js
test/cases/light-dom/src/components/navigation.js
test/cases/nested-elements/nested-elements.spec.js
test/cases/nested-elements/src/components/header.js
test/cases/nested-elements/src/pages/index.js
test/cases/render-from-html/render-from-html.spec.js
test/cases/render-from-html/src/components/header.js
test/cases/single-element/single-element.spec.js

resolves #51 
1. Update _dom-shim.js_ to correctly have the `<template>` tag logic inside `HTMLTemplateElement`
1. Updated specs slightly to reflect correct `<template>` implementation
1. Update documentation site off of incorrect `<template>` implementation
1. [x] ~~Make sure `this.mode` works from `attachShadow`~~ - https://github.com/ProjectEvergreen/wcc/issues/65
1. [x] Downstream sanity testing
- WC@TheEdge
- Greenwood
1. [x] Cross reference with `getInnerHTML` to make sure things are / will be still compatible -#16
1. [x] do we need a `get innerHTML` for `HTMLTemplateElement`? - tracked in #66 
1. [x] Create a discussion for better way to use `<templates>` but with variables / template literal placeholders. Or just create  render functions?....  But then you lose the free …

fix `HTMLTemplateElement` implementation to reflect standards behavior

---

README.md
package-lock.json
package.json
rollup.config.js
src/wcc.js

In support of integrating with CJS based projects like Eleventy, using Rollup to provide a temporary "dist" version of WCC for projects that can't support ESM directly.
1. Added Rollup and a `dist` command to generate a single bundle of `wcc`
1. Linked to `prepublish` script to make sure it gets run on each publish
1. Add documentation

CommonJS distribution version

---

README.md
package.json
rollup.config.js

#67 
Found this issue when using in https://github.com/ProjectEvergreen/eleventy-plugin-wcc
```shell
% npm run demo
> eleventy-plugin-wcc@0.0.1 demo
> npm run build -- --serve
> eleventy-plugin-wcc@0.0.1 build
> npm run clean && eleventy "--serve"
> eleventy-plugin-wcc@0.0.1 clean
> rimraf ./_site
[11ty] Eleventy CLI Fatal Error: (more in DEBUG output)
[11ty] 1. Error in your Eleventy config file '/Users/owenbuckley/Workspace/project-evergreen/repos/eleventy-plugin-wcc/.eleventy.js'. (via EleventyConfigError)
[11ty] 2. Must use import to load ES Module: /Users/owenbuckley/Workspace/project-evergreen/repos/eleventy-plugin-wcc/node_modules/wc-compiler/dist/wcc.dist.js
[11ty] require() of ES modules is not supported.
[11ty] require() of …
```

handling for ESM (`type="module"`) packages

---

src/wcc.js
test/cases/nested-elements/src/pages/index.js

resolves #25
1. If a customElement has not been defined, just show a warning message instead of failing outright
> _WARNING: customElement `<xxx-yyyyy>` is not defined.  You may not have imported it yet._

Gracefully handle undefined custom elements with `console.warn` message

---

src/dom-shim.js
test/cases/empty/empty.spec.js
test/cases/empty/src/empty.js

resolves #4 
1. Handle empty component compilation and test case
For reference, Chrome returns `''` for the custom element when running in the browser, so presuming this is per "the spec".
> _Just through the way inheritance works I guess but setting innerHTML in the `Element.constructor` triggers the setter, hence the guard to ensure the presence of content for `HTMLTemplateElement`_

empty component should not break compiler

---

src/wcc.js
test/cases/nested-elements/src/components/footer.js

…lements.define calls
resolves #97 
1. Check for `Literal` vs `TemplateLiteral` when serializing custom elements tags
1. Add test case

check for literals vs template literal for tag name quotes in `customElements.define` call

---

src/jsx-loader.js
test-exp-loader.js

N / A
1. Realized tests should really be using the actual loader, not a mock.  Mean setting `shortCircuit` on the custom loader

use underlying JSX loader in testing loader

---

src/jsx-loader.js
src/wcc.js

related to #36 
1. Remove dependencies on Node specific `path` and `url` dependencies
1. [x] Clean up _jsx-loader.js_
----
Unfortunately it seems like `fs` might be here with us a bit per https://github.com/ProjectEvergreen/greenwood/issues/953#issuecomment-1345438259

remove `path` and `url` node dependencies from main entry points

---

.eslintrc.cjs
.ls-lint.yml
docs/pages/docs.md
docs/pages/examples.md
docs/pages/index.md
package-lock.json
package.json

N / A
1. Apply eslint to all documentation examples
1. Also add plugin `describe.only` specs

eslint all documentation examples

---

docs/pages/docs.md
src/wcc.js
test/cases/no-wrapping-entry-tag/no-wrapping-entry-tag.spec.js
test/cases/no-wrapping-entry-tag/src/no-wrap.js

resolves #114 
1. Add support for a an option to enable / disable the presence of a wrapping tag for entry files to `renderToString`
1. [x] [how to best handle `metadata` and entry point flag](https://github.com/ProjectEvergreen/wcc/issues/114#issuecomment-1480467315) - https://github.com/ProjectEvergreen/wcc/issues/117
1. [x] Documentation

add no wrapping entry tag option for renderToString

---

src/wcc.js
test/cases/no-export/no-export.spec.js

resolves #124 
1. Don't log out when checking for custom elements in `initializeCustomElement `
1. Add logging if `renderToString` entry point is not a custom element
1. Updated no export spec

enhancement/issue 124 refactor handling and logging for entry points and dependencies with no custom element `export`

---

README.md
docs/pages/docs.md
docs/pages/index.md
src/dom-shim.js
test/cases/attributes/attributes.spec.js
test/cases/attributes/src/components/counter.js
test/cases/children-and-slots/children-and-slots.spec.js
test/cases/custom-extension/custom-extension.spec.js
test/cases/get-data/get-data.spec.js
test/cases/get-data/src/components/counter.js
test/cases/nested-elements/nested-elements.spec.js
test/cases/nested-elements/src/components/header.js
test/cases/render-from-html/render-from-html.spec.js
test/cases/single-element/single-element.spec.js

resolves #126 
1. Find / replace all instances of `shadowroot` attribute with "new" spec compliant `shadowrootmode`
1. Update documentation and test cases
----
Can confirm no more issues with this now enabled
**Before**
**After**

feature/issue 126 migrate to `shadowrootmode` attribute

---

src/jsx-loader.js
test/cases/jsx-shadow-dom/jsx-shadow-dom.spec.js

resolves #109 
> See an example [here](https://github.com/ProjectEvergreen/greenwood-demo-adapter-vercel/pull/24)
1. Leverage [`getRootNode`](https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode) for `this` references inside DSD generated by JSX
----
This should be merged **_after_** #129 since that PR adds a missing test case and does a fair amount of refactoring

enhancement/use `getRootNode` for `this` references in JSX DSD

---

src/dom-shim.js

resolves #15 
1. Move `attachShadow` and `innerHTML` getter to `Element` base case, [as per MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/)
----
TODO
1. [x] Greenwood test case sanity check

bug/issue 15 refactor DOM methods to correct base class implementation

---

src/dom-shim.js

resolves #147 
https://github.com/ProjectEvergreen/wcc/assets/895923/f8e194ae-1831-488c-a821-b8d491c9c2db
1. Make DOM globals "idempotent" to support multiple reloads in the same process

bug/issue 147 re-use existing DOM shim globals if they exist

---

src/dom-shim.js
src/wcc.js

resolves #144
https://github.com/ProjectEvergreen/wcc/assets/895923/0af35395-9292-4bfe-a5c4-fe8c664be181
1. Only use `customElementsRegistry` for checking if a custom element definition exists
1. Refactor `customElementsRegistry` to be a set
1. All tests still passing in Greenwood
----
See https://github.com/ProjectEvergreen/wcc/discussions/145 for more on this topic

bug/issue 144 check CE registry before assuming a custom element definition exists

---

src/jsx-loader.js

resolves #150 
1. Fixed the **acorn-jsx** import to use our fork

bug/fix import reference to forked acorn-jsx-esm package

---

docs/pages/index.md
src/dom-shim.js
test/cases/constructable-stylesheet/constructabe-stylesheet.spec.js
test/cases/constructable-stylesheet/src/components/header/header.js
test/cases/constructable-stylesheet/src/pages/index.js
test/cases/import-attributes/import-attributes.spec.js

resolves #152 
1. Adds a shim for `CSSStyleSheet`
1. Add test case
1. Document support (just as no-ops for now, but can certainly flesh this out more as needed by the community and / or use cases)
1. [x] Do / should we need to polyfill anything else?
1. [x] Update documentation
1. [x] Add test case (or maybe wait as part of #152 ?)

feature/issue 153 `CSSStyleSheet` in DOM Shim

---

src/wcc.js
test/cases/render-from-html/render-from-html.spec.js
test/cases/render-from-html/src/components/header.js

resolves #165 
1. Reduce double instantiation in `renderFromHTML`
1. Add test case

bug/issue 165 no premature double custom element instantiation in `renderFromHTML`

---

README.md
docs/pages/examples.md
sandbox/index.html

https://github.com/ProjectEvergreen/greenwood/issues/978
1. Update / refresh for new website cutover

chore/updates for new Greenwood website

---

package-lock.json
package.json
src/jsx-loader.js
src/wcc.js
test/cases/attributes/src/components/counter.js
test/cases/jsx/src/counter.jsx

resolves #174 
1. Swap out **escodegen** with [**astring**](https://github.com/davidbonnet/astring) since escodegen seems to be unmaintained (and now we can archive our custom fork since astring is ESM compatible)
1. [x] validate in https://github.com/ProjectEvergreen/greenwood/pull/1321

bug/issue 174 swap escodegen with astring for modern JS syntax support

---

docs/pages/examples.md
src/dom-shim.js
src/wcc.js
test/cases/attributes/src/components/counter.js
test/cases/get-data/src/components/counter.js
test/cases/nested-elements/src/components/header.js

- replaced deprecated method getInnerHTML with getHTML and made this return the HTML wrapped in a DSD template when the serializableShadowRoots option is set to true, which is according to the specs
- removed adding `<template shadowrootmode="open">` when `innerHTML` of `<template>` is set since this will now correctly be added when the `getHTML` method of the element is called with the option `{ serializableShadowRoots: true }`
- updated tests
- added missing closing square bracket in selector: `this.shadowRoot.querySelector('script[type="application/json"')`
This change makes sure that a web component that has its Shadow DOM set through innerHTML instead of a template like this:
```
const shadowRoot = this.attachShadow({mode: 'open'});
shadowRoot.innerHTML = `...`;
```
can also be …

feature/issue 177 Replaced deprecated method getInnerHTML with getHTML

---

docs/pages/docs.md

resolves #181 
1. Document usage of `shadowRoot.innerHTML`
1. Fixup data loading example to be a bit more complete

docs/document usage of setting `shadowRoot.innerHTML`

---

.github/workflows/ci.yml
package-lock.json
package.json
src/dom-shim.js
src/index.d.ts
src/jsx-loader.js
src/wcc.js
tsconfig.json

resolves #193 
1. Add `type` definitions for `renderFromHTML` and `renderToString`
1. Add basic type checking for CI (applied some low-handing fruit recommendations)
1. Update _package.json_ to export types and adopt `exports` field (will consider this a breaking change)
1. [x] refine metadata type (and types field?) - https://merry-caramel-524e61.netlify.app/docs/#metadata
- default values
- required vs optional
1. [x] Do we need to expose any types via _package.json_?
- metadata as a type?
1. [x] (nice to have / good first issue) had to add a number of `@ts-ignores` since a lot of the AST related work threw TS errors - https://github.com/ProjectEvergreen/wcc/issues/197

feature/issue 193 WCC types

---

package.json

related to #193 
1. Forgot to add top-level `types` field (primarily for NPM badge)

feature/issue 193 top level `types` field in package.json

---

src/index.d.ts
src/wcc.js

resolves #203 
1. Correctly export API functions and types
----
Removed the types from the source since it was causing conflicts
But it all still works anyway, like hovering over the export in a test case

bug: #203 correct export types and functions
